# permissions for end users to view fusedemoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fusedemo-viewer-role
rules:
- apiGroups:
  - fuse.github.com
  resources:
  - fusedemoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fuse.github.com
  resources:
  - fusedemoes/status
  verbs:
  - get
