
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - fuse.github.com
  resources:
  - fusedemoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fuse.github.com
  resources:
  - fusedemoes/finalizers
  verbs:
  - update
- apiGroups:
  - fuse.github.com
  resources:
  - fusedemoes/status
  verbs:
  - get
  - patch
  - update
